[package]
edition = "2021"
name = "lurkr"
version = "0.2.0"
[dependencies]
config = "*"
env_logger = "*"
log = "*"
rand = "*"
regex = "*"
rustls = "*"
serde = "*"
serde_derive = "*"
structopt = "*"
webpki = "*"
tokio-rustls = "*"
rustls-pemfile = "*"
ring = "*"
rcgen = "*"

[dependencies.tokio]
features = ["full"]
version = "*"
