[package]
edition = "2021"
name = "lurkr"
version = "0.3.0"
[dependencies]
anyhow = "*"
env_logger = "*"
log = "*"
rand = "*"
regex = "*"
rustls = "*"
serde = "*"
serde_derive = "*"
structopt = "*"
webpki = "*"
tokio-rustls = "*"
rustls-pemfile = "*"
ring = "*"
rcgen = "*"
indexmap = "*"

[dependencies.tokio]
features = ["full"]
version = "*"

[dependencies.hyper]
features = ["full"]
version = "*"

[dependencies.config]
features = ["preserve_order"]
version = "*"

