name: Release Software

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: thecubic/lurkr:latest
      # - name: Checkout Repository
      #   uses: actions/checkout@v4
      # - name: Use Podman Build and Push Action
      #   uses: Frozen-Tapestry/container-action@v1
      #   with:
      #     login_registry: ghcr.io
      #     login_username: ${{ secrets.REGISTRY_USERNAME }}
      #     login_password: ${{ secrets.REGISTRY_PASSWORD }}
      #     tags: ghcr.io/thecubic/lurkr:latest
      #     dockerfile: Dockerfile
      #     security: |
      #       --security-opt=seccomp=unconfined
      #       --security-opt=apparmor=unconfined
      #     push: true